version: '2'

networks:
  basic:

services:
  eat.ai.webapi:
    container_name: eat.ai.webapi
    image: tensorflow/tensorflow:latest-py3
    environment:
      - FLASK_APP=app.py
    working_dir: '/usr/local/eat'
    ports:
      - "8088:5000"
    tty: true
    volumes:
      - /usr/local/eat:/usr/local/eat
    command: /usr/local/eat/start.sh
    networks:
      - basic


