version: '2'

networks:
  basic:

services:
  eat.ai.webapi:
    image: tensorflow/tensorflow:latest-py3
    environment:
      - FLASK_APP=app.py
    ports:
      - "8088:5000"
    command: sh -c '/usr/local/eat/start.sh'
    volumes:
      - .:/usr/local/eat
    container_name: eat.ai.webapi
    networks:
      - basic


